/**
 * cities
 * food
 * landmarks
 * famous people
 * sports
 * music
 */


const words = [
    [
        "TORONTO",
        "MONTREAL",
        "VANCOUVER",
        "EDMONTON",
        "CALGARY",
        "OTTAWA",
        "SASKATCHEWAN",
        "BANFF NATIONAL PARK",
        "NIAGARA FALLS",
        "LAKE LOUISE",
        "CHATEAU FRONTENAC",
        "CN TOWER",
        "STANLEY PARK",
        "CAPILANO SUSPENSION BRIDGE",
        "KEANNU REEVES",
        "JUSTIN BIEBER",
        "DRAKE",
        "THE WEEKND",
        "SETH ROGAN",
        "SHANIA TWAIN",
        "WAYNE GRETZKY",
        "GEORGE ST PIERRE",
        "SIDNEY CROSBY",
        "STEVE NASH",
        "MARIO LEMIEUX",
        "PENNY OLEKSIAK",
        "MAPLE SYRUP",
        "BEAVERTAIL",
        "CANADA GOOSE",
        "TIM HORTONS"
    ],
    [
        "WINDOWS MILLENIUM",
        "LINUX",
        "ANDROID",
        "APPLE IPHONE",
        "MICROSOFT OFFICE",
        "ALPHABET INC",
        "AMAZON",
        "NVIDIA",
        "SAMSUNG GALAXY",
        "DELL LATITUDE",
        "MARK ZUCKERBERG",
        "SUNDAR PICHAI",
        "JEFF BEZOS",
        "TESLA",
        "ELON MUSK",
        "JAVASCRIPT",
        "PYTHON",
        "JAVA",
        "MACHINE LEARNING",
        "ARTIFICIAL INTELLIGENCE",
        "DATA SCIENCE",
        "COMPUTER PROGRAMMER",
        "EL CAPITAIN",
        "HIGH SIERRA",
        "BIG SUR",
        "LENOVO THINKPAD",
        "BILL GATES",
        "SAL KHAN",
        "INDRA NOOYI"
    ],        
    [
        "BILLIE JEAN KING",
        "TIGER WOODS",
        "MICHAEL SCHUMACHER",
        "DAVID BECKHAM",
        "FLOYD MAYWEATHER JR",
        "SHAQUILLE ONEAL",
        "KOBE BRYANT",
        "CONOR MCGREGOR",
        "LIONEL MESSI",
        "CRISTIANO RONALD",
        "VANCOUVER CANUCKS",
        "MANNY PACQUIAO",
        "ROGER FEDERER",
        "LEWIS HAMILTON",
        "TOM BRADY",
        "MARTINA NAVRATILOVA",
        "FC BARCELONA",
        "REAL MADRID CF",
        "MAYERN MUNICH",
        "LIVERPOOL",
        "MANCHESTER CITY",
        "CHELSEA",
        "ARSENAL",
        "PARIS SAINT GERMAIN",
        "MATS SUNDIN",
        "MANCHESTER UNITED",
        "MICHAEL JORDAN",
        "CANELO ALVAREZ",
        "ZLATAN IBRAHIMOVIC",
        "LEBRON JAMES"
    ],
]

export default words;