 const words = [
    ["TORONTO", "MONTREAL", "VANCOUVER", "EDMONTON", "CALGARY", "OTTAWA", "SASKATCHEWAN", "SCARBORO TOWN CENTRE"],
    ["NEW YORK CITY", "LOS ANGELES", "CHICAGO", "SAN FRANCISCO", "NEW MEXICO", "SAN DIEGO", "OKLAHOMA"],
    ["MAPLE LEAFS", "MANCHESTER UNITED", "RONALD", "MICHAEL JORDAN", "WAYNE GRETZKY", "ZULTAN IBRAHIMOVICH", "LEBRON JAMES"],
]

export default words;